### ISSUE TITLE
ToDo /Remember

### ISSUE THREAD

**Issue by UnderDev** [codevonnie/fourthyearproject#8]
***Tasks To Keep In Mind***

**Important** - Change [ ] to [x] if task is finished

- [x] Shorten Auth0 Token / Login details Expiry Time
- [x] Timeout on Neo4j Queries very long when not Correct 
- [x] Storage Of Passwords in the database Encrypted(not plain text)
- [x] Company Registration Validation
- [x] Remove All WhiteSpaces on inputs from user creating/updating etc
- [x] Validation On App inputs
- [x] Validation On WebApp inputs
- [x] Google Maps on Web App
- [x] Messaging Server between App/WebApp (Person->Business)
- [x] Convert all inputs (EXCEPT PASSWORDS) to lowercase before storing
- [x] Host Web App (Hosted on Azure)
- [x] Add Analytics (Bar Chart of Busiest/Slowest Months and Top Visited)

**Comment by codevonnie** [comment]
Updated some of the above that have been completed
